name: Download and Update

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set git user and email  
        uses: fregante/setup-git-user@v1
          
      - name: Run update script
        run: |
          bash update-repo.sh
