name: Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GHCR_TOKEN }}
        
      - name: Set git user and email  
        uses: fregante/setup-git-user@v1
          
      - name: Run update script
        run: bash update.sh
